
// Objective-C API for talking to the following Go packages
//
//	github.com/celer-network/goCeler/mobile
//	github.com/ethereum/go-ethereum/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_FRAMEWORK_H__
#define __Mobile_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Geth.objc.h"
#include "universe.objc.h"

#endif
